### PR TITLE
Propose Hands-On Programming with R

### PR DESCRIPTION
**Pull request by garrettgman**
for bookdown.org

### CODE REVIEW

**Comment by garrettgman** [comment]
Thanks @yihui. Updated and redeployed now.

**Comment by yihui** [comment]
Sorry, but I forgot to mention that the backslash was necessary in url, i.e. `https\://rstudio-education.github.io/hopr/`. And you didn't update the `docs` folder: https://github.com/rstudio-education/hopr/tree/master/docs

**Comment by garrettgman** [comment]
I added the missing backslash to the index url and reconfigured travis to update the docs folder (updated).

**Comment by garrettgman** [comment]
Thanks @yihui

**Pull request merged**
