### PR TITLE
Update link for Understanding the Whole Child

### PR DESCRIPTION
**Pull request by nathalieyuen**
Hi!

Would it be possible to update the link for Understanding the Whole Child: Prenatal Development through Adolescence (Paris et al., added 2021-06-08)?

New link: https://bookdown.org/nathalieyuen/understanding-the-whole-child/

Thanks for your help!

(Hope I'm doing this right.)

### CODE REVIEW

**Comment by cderv** [comment]
Hello @nathalieyuen, 

Your book is already published on bookdown.org. There is no need to add the book using the `staging.txt` mechanism which is for external books. 

For book published on bookdown.org, the link are created automatically and the website is updated weekly on Thursday. So https://bookdown.org/nathalieyuen/understanding-the-whole-child already exists and it will be fetched next Thursday to be updated on this page https://bookdown.org/home/archive/

Is that what you are expecting ?

**Comment by nathalieyuen** [comment]
> Hello @nathalieyuen,
> 
> Your book is already published on bookdown.org. There is no need to add the book using the `staging.txt` mechanism which is for external books.
> 
> For book published on bookdown.org, the link are created automatically and the website is updated weekly on Thursday. So https://bookdown.org/nathalieyuen/understanding-the-whole-child already exists and it will be fetched next Thursday to be updated on this page https://bookdown.org/home/archive/
> 
> Is that what you are expecting ?

Hi @cderv,

Thanks for this info!

I was concerned because I deleted the files for https://bookdown.org/nathalieyuen/paris-et-al-child-bookdown/ and now the link on the current archive page leads to a 404 page not found error.  I'm guessing this will all be resolved on Thursday with the update.

Thanks again!

**Comment by cderv** [comment]
> I was concerned because I deleted the files for bookdown.org/nathalieyuen/paris-et-al-child-bookdown and now the link on the current archive page leads to a 404 page not found error. I'm guessing this will all be resolved on Thursday with the update.

Yes it should. I'll look out for it tomorrow.

**Comment by cderv** [comment]
Hi @nathalieyuen, 

Your old book has correctly been unlisted from archive page because your removed it from bookdown.org

For the new book, it has not been found because the publication is not correct, or at least what is expected. 

Your main url: https://bookdown.org/nathalieyuen/understanding-the-whole-child/
is pointing to https://bookdown.org/nathalieyuen/understanding-the-whole-child/_book/acknowledgements.html and not an index page. it seems you don't have a index.Rmd in your book, have you ? 

It points currently to `acknowledgment.html` because it is the first HTML file alphabetically in your published folder.  Usually, you have the first page of the book to be an index.html (HTML convention): 
* published: https://bookdown.org/yihui/rmarkdown-cookbook/
* Rmd source: https://github.com/yihui/rmarkdown-cookbook/blob/master/index.Rmd becomes https://bookdown.org/yihui/rmarkdown-cookbook/index.html

Also published book usually don't have the `_book/` folder : only what is inside the book folder is published. For example see this URL: https://bookdown.org/yihui/rmarkdown-cookbook/workflow.html

See here how to publish using bookdown function: https://bookdown.org/home/about/#3-publish

We need to make this expected content so that it gets correctly listed.

**Comment by nathalieyuen** [comment]
> Your main url: https://bookdown.org/nathalieyuen/understanding-the-whole-child/
> is pointing to https://bookdown.org/nathalieyuen/understanding-the-whole-child/_book/acknowledgements.html and not an index page. it seems you don't have a index.Rmd in your book, have you ?

I was wondering about why the book was not loading to the index.html page (and why it pointed to acknowledgment.html).

I figured out what the issues were and everything should be loading correctly now.

Thanks again for all your help with this!

**Comment by cderv** [comment]
Great! 

I trickered a new update of the website manually. you book should now be listed as you expect.

**Pull request closed without merging**
