### PR TITLE
Add rOpenSci dev guide to archive page?

### PR DESCRIPTION
**Pull request by maelle**
Thank you :smiley_cat:

### CODE REVIEW

**Comment by maelle** [comment]
Ah cool 😁 We were waiting for our book cover (now available), do you re-scrape the metadata regularly? Thanks in any case!

**Comment by yihui** [comment]
Sure. I'll do that in a minute!

**Comment by yihui** [comment]
Done.

**Comment by maelle** [comment]
Thank you so much!

**Pull request closed without merging**
