### PR TITLE
Add rmarkdown cookbook to homepage

### PR DESCRIPTION
**Pull request by cderv**
As it is soon to be published I think we can pin it to home page on bookdown.org. What do you think ?

### CODE REVIEW

**Comment by cderv** [comment]
I saw your other comment. Not sure why it is taking so long in travis. The time limit has been reached here. 
Maybe we can cache more things or do things differently to more time consuming ? there some urls with error and maybe it is taking to long to see that they can't be reached.

**Comment by yihui** [comment]
I have a cache file on my computer, so it wouldn't take that long for me. The cache file is not available to Travis, which led to the timeout.

**Comment by cderv** [comment]
OK thanks! One more thing I'll note and how all this works :) 
Maybe there is a way to stop travis from running 50min when another file thant `staging.txt` is modified. It seems to me we are using resources on travis for nothing. IMO that is too bad.

**Comment by yihui** [comment]
That's a good idea. Please feel free to send a PR.

**Pull request merged**
