### PR TITLE
add the book Data Analytics - A Small Data Approach

### PR DESCRIPTION
**Pull request by yihui**
This book uses the tufte style. Not sure if its info can be scraped successfully. Let's see.

### CODE REVIEW

**Comment by yihui** [comment]
Result: https://github.com/rstudio/bookdown.org/runs/2349432673#step:8:35

The index page of the book lacks some critical information in the HTML source: title, author, date, and summary.

**Comment by yihui** [comment]
The repo that contains the book output is here: https://github.com/analyticsbook/analyticsbook.github.io

- The title is not properly set: https://github.com/analyticsbook/analyticsbook.github.io/blob/751f218cabccaedb882bd89fa6da4ec712b0b0fd/index.html#L29
- It doesn't have author or date info like this: https://github.com/rstudio/bookdown/blob/2f39faf187f05c2287316d42c22d83e117ad2d57/index.html#L248-L249
- It doesn't have a summary like https://github.com/rstudio/bookdown/blob/2f39faf187f05c2287316d42c22d83e117ad2d57/index.html#L14

**Comment by softwaredeng** [comment]
@yihui  I have added meta tags on title, name, date, and description. let me know if this works. Thanks for the help!

**Comment by yihui** [comment]
Looks good now: https://github.com/rstudio/bookdown.org/runs/2367525018?check_suite_focus=true#step:8:46 Thanks!

BTW, I assume these tags were automatically generated, i.e., you added the information in Rmd source files, instead of manually editing the HTML output file. The book info is scaped automatically every week, so you need to make sure the required info will always be there.

**Comment by softwaredeng** [comment]
awesome, thank you! Just curious, is there any fixed time for the scraping (or is there a way we can figure out the time)? 

Yeah we generated the tags thru the index source file and used regex to remove some of the information including title/date/author (avoid displaying them on the landing). It is a bit hacky but is in one shell script.

**Comment by yihui** [comment]
As long as you have automated the job of creating those tags, you should be fine.

We use this cron job to update books on this site: https://github.com/rstudio/bookdown.org/blob/master/.github/workflows/update_books_infos.yaml#L4

**Pull request merged**
