### PR TITLE
Pin two new book

### PR DESCRIPTION
**Pull request by cderv**
This PR pins two new books on the main page 

* https://forwards.github.io/rdevguide
* https://smltar.com/

### CODE REVIEW

**Comment by cderv** [comment]
They are missing a cover... This need to be fixed before we can merge this.

Other candidates are: 

* https://book.javascript-for-r.com/
* https://unleash-shiny.rinterface.com/ 

But not sure they have cover either

**Comment by cderv** [comment]
We still need a second book with a cover

**Comment by rubend18** [comment]
Please add
https://rubend18.github.io/manual-de-r/

**Comment by cderv** [comment]
@rubend18 please follow https://bookdown.org/home/about/#how-to-get-your-book-listed-on-bookdownorg

You need to check you have all the information and then open a PR with `staging.txt` following what is explained in the link above. 

Thank you.

**Pull request merged**
