### PR TITLE
Update staging.txt

### PR DESCRIPTION
**Pull request by gwmatthews**
Request inclusion on featured page.

### CODE REVIEW

**Comment by cderv** [comment]
Hi ! 

Thanks for the PR. However, several comments/questions: 

* Your book is already on bookdown.org (https://bookdown.org/geoslack/ethics-guidebook/) so it will be listed automatically at next update
* It seems you are hosting the book also outside of bookdown.org (https://gwmatthews.github.io/ethics/) - we can use this url instead in the book listing if you prefer. To do that, you would remove the book from bookdown.org content, and modify this PR to have only your external url in the first line of `staging.txt`
* This PR you opened with `staging.txt` is aimed at providing external url for a book to be listed. See https://bookdown.org/home/about/#how-to-get-your-book-listed-on-bookdownorg 

What is the best choice for you ?

**Comment by gwmatthews** [comment]
Hi Thanks for getting back to me about this. I was honestly a bit confused about the method for getting a book listed. I will modify the PR to contain the url to the text on github -- your second option. Sorry for the mix up!

-George

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cderv** [comment]
Great thanks ! Do not forget to delete the one in https://bookdown.org/geoslack/ethics-guidebook/ or it will be listed twice. 
If you want to keep it for any reason, we need to exclude it from the list.  Do you want to keep the one published in bookdown.org ?

**Comment by cderv** [comment]
> But the link on the "books" page at Bookdown returns a 404 error. 

It will be removed at next website update.

**Pull request merged**
