### PR TITLE
Add geocomputation with R

### PR DESCRIPTION
**Pull request by Robinlovelace**
The first book on the front page about space I think - plenty about temporal data but little on space, until now!

### CODE REVIEW

**Comment by yihui** [comment]
BTW, have you got the front cover image yet?

**Comment by Robinlovelace** [comment]
But it will take a few weeks to update it. As discussed with @nowosad we're thinking of having a competition to get people participating in spatial data viz.

**Comment by yihui** [comment]
I recommend you to optimize the PNG image, and probably also reduce its size (currently it is 1.2MB).

**Comment by Robinlovelace** [comment]
Will do, thanks for the suggestion. Regarding the size, I was following this: https://www.tidytextmining.com/images/cover.png 

Plan to update it to 424 x 648 as per your one (wish I looked at that cover first!):

``` r
i = magick::image_read("https://bookdown.org/yihui/bookdown/images/cover.jpg")
magick::image_info(i)
#>   format width height colorspace matte filesize density
#> 1   JPEG   424    648       sRGB FALSE    32595   96x96
```

Created on 2018-08-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by Robinlovelace** [comment]
Update: job done, down to 34 KB thanks to smaller size and the imageprocessor!

**Comment by yihui** [comment]
Great! I'll republish bookdown.org later.

**Comment by yihui** [comment]
FYI it is on the homepage now: https://bookdown.org

**Pull request merged**
